import React, { useState } from "react";
import axios from "axios";
import { format } from "date-fns";
import { FileCsv, FilePdf, FileText, CircleNotch } from "@phosphor-icons/react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const RANGES = [
  { label: "1H", value: "1h" },
  { label: "6H", value: "6h" },
  { label: "24H", value: "24h" },
  { label: "7D", value: "7d" },
  { label: "30D", value: "30d" },
];

const ComplianceExport = () => {
  const [range, setRange] = useState("24h");
  const [loading, setLoading] = useState(false);

  const fetchReport = async () => {
    const res = await axios.get(`${API}/reports/compliance?time_range=${range}`);
    return res.data;
  };

  const handleCSV = async () => {
    setLoading(true);
    try {
      const report = await fetchReport();
      let csv = `Compliance Report\nGenerated,${format(new Date(report.report_generated), "dd/MM/yyyy HH:mm:ss")}\nRange,${report.range}\n\n`;
      csv += "Instrument ID,Name,Unit,Low Limit,High Limit,Readings,Min,Max,Mean,Out of Spec,Compliance %\n";
      report.compliance_data.forEach((r) => {
        csv += `${r.instrument_id},${r.instrument_name},${r.unit},${r.low_limit},${r.high_limit},${r.readings_count},${r.min_value},${r.max_value},${r.mean_value},${r.out_of_spec_count},${r.compliance_pct}%\n`;
      });
      csv += `\nAlert Summary\n`;
      csv += `Compliance Alerts,${report.alert_summary.compliance}\n`;
      csv += `Leak Alerts,${report.alert_summary.leak}\n`;
      csv += `Anomaly Alerts,${report.alert_summary.anomaly}\n`;
      csv += `Offline Alerts,${report.alert_summary.offline}\n`;
      csv += `Total Leak Events,${report.total_leak_events}\n`;

      const blob = new Blob([csv], { type: "text/csv" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `compliance_report_${range}.csv`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success("CSV report downloaded");
    } catch (e) {
      toast.error("Failed to generate CSV");
    } finally {
      setLoading(false);
    }
  };

  const handlePDF = async () => {
    setLoading(true);
    try {
      const report = await fetchReport();
      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.setTextColor(0, 122, 255);
      doc.text("Compliance Report", 14, 20);
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text("Water Reticulation Digital Twin", 14, 28);
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(
        `Generated: ${format(new Date(report.report_generated), "dd/MM/yyyy HH:mm:ss")}  |  Range: ${report.range}`,
        14,
        35
      );

      // Compliance Table
      doc.setFontSize(14);
      doc.setTextColor(0);
      doc.text("Water Quality Compliance", 14, 48);

      autoTable(doc, {
        startY: 52,
        head: [
          [
            "Instrument",
            "Unit",
            "Low",
            "High",
            "Min",
            "Max",
            "Mean",
            "Out of Spec",
            "Compliance",
          ],
        ],
        body: report.compliance_data.map((r) => [
          `${r.instrument_name}\n(${r.instrument_id})`,
          r.unit,
          r.low_limit,
          r.high_limit,
          r.min_value,
          r.max_value,
          r.mean_value,
          r.out_of_spec_count,
          `${r.compliance_pct}%`,
        ]),
        theme: "grid",
        headStyles: { fillColor: [0, 122, 255], fontSize: 8 },
        bodyStyles: { fontSize: 8 },
        columnStyles: { 8: { fontStyle: "bold" } },
      });

      // Alert Summary
      const y = doc.lastAutoTable.finalY + 12;
      doc.setFontSize(14);
      doc.text("Alert Summary", 14, y);

      autoTable(doc, {
        startY: y + 4,
        head: [["Alert Type", "Count"]],
        body: [
          ["Compliance", report.alert_summary.compliance],
          ["Leak", report.alert_summary.leak],
          ["Anomaly", report.alert_summary.anomaly],
          ["Offline", report.alert_summary.offline],
          ["Total Leak Events", report.total_leak_events],
        ],
        theme: "grid",
        headStyles: { fillColor: [255, 59, 48], fontSize: 9 },
        bodyStyles: { fontSize: 9 },
      });

      // Footer
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        "This report was auto-generated by the Digital Twin system.",
        14,
        pageHeight - 10
      );

      doc.save(`compliance_report_${range}.pdf`);
      toast.success("PDF report downloaded");
    } catch (e) {
      toast.error("Failed to generate PDF");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="grid-border p-4 md:p-6"
      style={{ backgroundColor: "#121212" }}
      data-testid="compliance-export"
    >
      <div className="flex items-center gap-2 mb-4">
        <FileText size={24} color="#007AFF" weight="duotone" />
        <h3
          className="text-xl md:text-2xl font-semibold tracking-tight"
          style={{ fontFamily: "Chivo, sans-serif", color: "#FFFFFF" }}
        >
          Compliance Reports
        </h3>
      </div>

      <div className="flex flex-wrap items-center gap-3">
        {/* Range selector */}
        <div
          className="flex items-center rounded-sm border overflow-hidden"
          style={{
            borderColor: "rgba(255, 255, 255, 0.1)",
            backgroundColor: "#1A1A1A",
          }}
          data-testid="report-range-selector"
        >
          {RANGES.map((r) => (
            <button
              key={r.value}
              onClick={() => setRange(r.value)}
              className="px-3 py-1.5 text-xs font-bold transition-colors"
              style={{
                backgroundColor:
                  range === r.value ? "#007AFF" : "transparent",
                color: range === r.value ? "#FFFFFF" : "#A3A3A3",
              }}
              data-testid={`report-range-${r.value}`}
            >
              {r.label}
            </button>
          ))}
        </div>

        {/* Export buttons */}
        <button
          onClick={handleCSV}
          disabled={loading}
          className="flex items-center gap-1.5 px-4 py-2 rounded-sm border text-sm font-medium hover:border-[#34C759] transition-colors disabled:opacity-50"
          style={{
            borderColor: "rgba(255, 255, 255, 0.1)",
            color: "#34C759",
            backgroundColor: "#1A1A1A",
          }}
          data-testid="compliance-csv-button"
        >
          {loading ? (
            <CircleNotch size={16} className="animate-spin" />
          ) : (
            <FileCsv size={16} weight="duotone" />
          )}
          Export CSV
        </button>
        <button
          onClick={handlePDF}
          disabled={loading}
          className="flex items-center gap-1.5 px-4 py-2 rounded-sm border text-sm font-medium hover:border-[#FF3B30] transition-colors disabled:opacity-50"
          style={{
            borderColor: "rgba(255, 255, 255, 0.1)",
            color: "#FF3B30",
            backgroundColor: "#1A1A1A",
          }}
          data-testid="compliance-pdf-button"
        >
          {loading ? (
            <CircleNotch size={16} className="animate-spin" />
          ) : (
            <FilePdf size={16} weight="duotone" />
          )}
          Export PDF
        </button>
      </div>
    </div>
  );
};

export default ComplianceExport;
