import { format } from "date-fns";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export function generateComplianceCSV(report, range) {
  let csv = `Compliance Report\nGenerated,${format(new Date(report.report_generated), "dd/MM/yyyy HH:mm:ss")}\nRange,${report.range}\n\n`;
  csv += "Instrument ID,Name,Unit,Low Limit,High Limit,Readings,Min,Max,Mean,Out of Spec,Compliance %\n";
  report.compliance_data.forEach((r) => {
    csv += `${r.instrument_id},${r.instrument_name},${r.unit},${r.low_limit},${r.high_limit},${r.readings_count},${r.min_value},${r.max_value},${r.mean_value},${r.out_of_spec_count},${r.compliance_pct}%\n`;
  });
  csv += `\nAlert Summary\n`;
  csv += `Compliance Alerts,${report.alert_summary.compliance}\n`;
  csv += `Leak Alerts,${report.alert_summary.leak}\n`;
  csv += `Anomaly Alerts,${report.alert_summary.anomaly}\n`;
  csv += `Offline Alerts,${report.alert_summary.offline}\n`;
  csv += `Total Leak Events,${report.total_leak_events}\n`;

  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `compliance_report_${range}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function generateCompliancePDF(report, range) {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.setTextColor(0, 122, 255);
  doc.text("Compliance Report", 14, 20);
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Water Reticulation Digital Twin", 14, 28);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(
    `Generated: ${format(new Date(report.report_generated), "dd/MM/yyyy HH:mm:ss")}  |  Range: ${report.range}`,
    14,
    35
  );

  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Water Quality Compliance", 14, 48);

  autoTable(doc, {
    startY: 52,
    head: [
      [
        "Instrument",
        "Unit",
        "Low",
        "High",
        "Min",
        "Max",
        "Mean",
        "Out of Spec",
        "Compliance",
      ],
    ],
    body: report.compliance_data.map((r) => [
      `${r.instrument_name}\n(${r.instrument_id})`,
      r.unit,
      r.low_limit,
      r.high_limit,
      r.min_value,
      r.max_value,
      r.mean_value,
      r.out_of_spec_count,
      `${r.compliance_pct}%`,
    ]),
    theme: "grid",
    headStyles: { fillColor: [0, 122, 255], fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: { 8: { fontStyle: "bold" } },
  });

  const y = doc.lastAutoTable.finalY + 12;
  doc.setFontSize(14);
  doc.text("Alert Summary", 14, y);

  autoTable(doc, {
    startY: y + 4,
    head: [["Alert Type", "Count"]],
    body: [
      ["Compliance", report.alert_summary.compliance],
      ["Leak", report.alert_summary.leak],
      ["Anomaly", report.alert_summary.anomaly],
      ["Offline", report.alert_summary.offline],
      ["Total Leak Events", report.total_leak_events],
    ],
    theme: "grid",
    headStyles: { fillColor: [255, 59, 48], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
  });

  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    "This report was auto-generated by the Digital Twin system.",
    14,
    pageHeight - 10
  );

  doc.save(`compliance_report_${range}.pdf`);
}
